# Generated by Django 4.1.5 on 2023-01-07 07:11

import cpf_field.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_endereco', models.CharField(choices=[('Residencial', 'Residencia (PF)'), ('Trabalho', 'Trabalho (PF)'), ('Outros', 'Outros (PF/PJ)'), ('Razão Social', 'Razao Social (PJ)')], default='Residencial', max_length=15)),
                ('cep', models.CharField(blank=True, default='', max_length=8)),
                ('estado', models.CharField(blank=True, default='', max_length=2)),
                ('cidade', models.CharField(blank=True, default='', max_length=100)),
                ('bairro', models.CharField(blank=True, default='', max_length=100)),
                ('endereco', models.CharField(blank=True, default='', max_length=120)),
                ('complemento', models.CharField(blank=True, default='', max_length=120)),
                ('complemento2', models.CharField(blank=True, default='', max_length=120)),
                ('pais', models.CharField(default='Brasil', max_length=25)),
                ('ponto_referencia', models.CharField(blank=True, default='', max_length=120)),
                ('observacao', models.CharField(blank=True, default='', max_length=255)),
                ('ativo', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('oper', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Fone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_fone', models.CharField(choices=[('Residencial', 'Residencial'), ('Celular', 'Celular'), ('WhatsApp', 'Whatsapp'), ('Trabalho', 'Trabalho'), ('Outros', 'Outros')], default='Celular', max_length=15)),
                ('descricao', models.CharField(blank=True, max_length=100)),
                ('numero', models.CharField(max_length=20)),
                ('ativo', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('oper', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TenantSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_tenant_name', models.CharField(max_length=100)),
                ('system_tenant_logo', models.ImageField(blank=True, null=True, upload_to='tenant_company_logos/%Y/%m/%d/')),
                ('system_description', models.CharField(max_length=255)),
                ('authorized_by', models.CharField(default='FEALVES', max_length=15)),
                ('ativo', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('oper', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilDoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pessoa', models.CharField(choices=[('1', 'Administrador'), ('2', 'Cliente'), ('3', 'Colaborador(a)'), ('4', 'Parceiro(a), porém não-funcionário(a)')], default=2, max_length=1)),
                ('nome', models.CharField(blank=True, default='', max_length=100)),
                ('cpf', cpf_field.models.CPFField(blank=True, default='', max_length=11)),
                ('identidade', models.CharField(blank=True, default='', max_length=30)),
                ('sexo', models.CharField(choices=[('1', 'Masculino'), ('2', 'Feminino'), ('3', 'Outros')], default='Masculino', max_length=15)),
                ('data_nascimento', models.CharField(blank=True, default='', max_length=10)),
                ('estado_civil', models.CharField(choices=[('1', 'Casado(a)'), ('2', 'Solteiro(a)'), ('3', 'Divorciado(a)'), ('4', 'Viúvo(a)')], default=2, max_length=15)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pessoas_fotos/%Y/%m/%d/')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.URLField(blank=True, default='')),
                ('ativo', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('oper', models.IntegerField(default=0)),
                ('conjuge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.perfildousuario')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.endereco')),
                ('fones', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.fone')),
                ('tenant_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenantsystem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fone',
            name='tenant_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.tenantsystem'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='tenant_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.tenantsystem'),
        ),
    ]
