# Generated by Django 4.1.5 on 2023-01-07 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descricão')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tarefa')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descricão')),
                ('end_date', models.DateField(verbose_name='Data Final')),
                ('priority', models.CharField(choices=[('B', 'Baixa'), ('A', 'Alta'), ('M', 'Media')], max_length=1, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('PD', 'Pendente'), ('EX', 'Em execucão'), ('CD', 'Concluída')], max_length=2, verbose_name='Status')),
                ('category', models.ManyToManyField(to='core.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['id'],
            },
        ),
    ]
